trigger:
- main

pool:
  name: "Jaya2"
  # vmImage: 'Jaya2'  # Adjust for macOS if needed

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Download Hyperexecute CLI for macOS (adjust for other OS)
        name: Download HyperExecute CLI
        script: wget https://downloads.lambdatest.com/hyperexecute/darwin/hyperexecute
        
        # Grant execute permission to the downloaded binary
        name: Make HyperExecute executable
        script: chmod +x hyperexecute
        
        # Run Hyperexecute with user credentials and configuration file
        name: Run Hyperexecute Tests
        script: ./hyperexecute.exe --user jayak --key b4JOibh8UrnB8Ce2eL2VgHtc9P91eu4xCSc2IdXA7nibD30lX1 --config yaml/autosplit_linux.yaml

