version: 2.1
parameters:
  username:
    type: string
    default: "USERNAME"
  access_key:
    type: string
    default: "ACCESS_KEY"
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Download HE CLI"
          command: wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
      - run:
          name: "Permissions"
          command: chmod u+x hyperexecute
      - run:
          name: "Runner Command"
          command: ./hyperexecute --user pipeline.parameters.username --key pipeline.parameters.access_key --config yaml/autosplit_linux.yaml
workflows:
  build-and-test:
    jobs:
      - test-java
